# ================================================================================
# Here you decide which database to run on: Input --- mysql --- or --- mongodb ---
# ================================================================================
spring.profiles.active=mysql

# Application server configuration

server.address=0.0.0.0

# Defines the port where the API will run
server.port=8001

# MONGODB SETTINGS (Active when profile is 'mongodb')
# The host must be 'mongodb' to work inside the Docker network, exactly as defined in compose.yaml
spring.data.mongodb.uri=mongodb://mongodb:27017/sd3_users_db

# MYSQL SETTINGS (Active when profile is 'mysql')
# "mysql" refers to the Docker Compose service name (internal hostname)
spring.datasource.url=jdbc:mysql://mysql:3306/sd3db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MYBATIS CONFIGURATION (Only used by MySQL profile)
# Location of MyBatis XML mapper files
mybatis.mapper-locations=classpath:mappers/*.xml

# Enables automatic mapping from snake_case to camelCase
mybatis.configuration.map-underscore-to-camel-case=true

# Package where MyBatis entity aliases are located
mybatis.type-aliases-package=com.ideavoting.usersapi.infrastructure.mysql.entities

# MyBatis log - displays the query being executed
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
